import { defineDsBadge, DsBadgeElement } from './badge/badge.wc';
import { defineDsButton, DsButtonElement } from './button/button.wc';
import { defineDsCheckbox, DsCheckboxElement } from './checkbox/checkbox.wc';
import { defineDsInput, DsInputElement } from './input/input.wc';
import { defineDsLabel, DsLabelElement } from './label/label.wc';
import { defineDsLink, DsLinkElement } from './link/link.wc';
import { defineDsRadio, DsRadioElement } from './radio/radio.wc';
import { defineDsSelect, DsSelectElement } from './select/select.wc';
import { defineDsSeparator, DsSeparatorElement } from './separator/separator.wc';
import { defineDsSkeleton, DsSkeletonElement } from './skeleton/skeleton.wc';
import { defineDsSwitch, DsSwitchElement } from './switch/switch.wc';
import { defineDsToast, DsToastElement } from './toast/toast.wc';
import { defineDsTypography, DsTypographyElement } from './typography/typography.wc';

export { defineDsBadge, DsBadgeElement };
export { defineDsButton, DsButtonElement };
export { defineDsCheckbox, DsCheckboxElement };
export { defineDsInput, DsInputElement };
export { defineDsLabel, DsLabelElement };
export { defineDsLink, DsLinkElement };
export { defineDsRadio, DsRadioElement };
export { defineDsSelect, DsSelectElement };
export { defineDsSeparator, DsSeparatorElement };
export { defineDsSkeleton, DsSkeletonElement };
export { defineDsSwitch, DsSwitchElement };
export { defineDsToast, DsToastElement };
export { defineDsTypography, DsTypographyElement };

export const defineAllWebComponents = () => {
  defineDsBadge();
  defineDsButton();
  defineDsCheckbox();
  defineDsInput();
  defineDsLabel();
  defineDsLink();
  defineDsRadio();
  defineDsSelect();
  defineDsSeparator();
  defineDsSkeleton();
  defineDsSwitch();
  defineDsToast();
  defineDsTypography();
};
